### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Tomadoggy** [jmc265/rpi-433-v3#1]
Assistance if you can please...I wish to use the node red rpi-433-sniffer but am unable to install  npm install rpi-433-v3 on my Pi 4 (completely up to date).  Errors seen at install:

npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'

Here is the entire error log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'rpi-433-v3' ]
2 info using npm@6.14.8
3 info using node@v12.20.0
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose npm-session d3bd64801a187ceb
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 timing stage:rollbackFailedOptional Completed in 5ms
9 timing stage:runTopLevelLifecycles Completed in 107ms
10 verbose stack Error: Failed to parse json
10 verbose stack Unexpected end of JSON input while parsing near ''
10 verbose stack     at parseError (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:470:11)
10 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:105:26)
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:52:5
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
10 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
11 verbose cwd /home/pi
12 verbose Linux 5.4.79-v7l+
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "rpi-433-v3"
14 verbose node v12.20.0
15 verbose npm  v6.14.8
16 error code EJSONPARSE
17 error file /home/pi/package.json
18 error JSON.parse Failed to parse json
18 error JSON.parse Unexpected end of JSON input while parsing near ''
19 error JSON.parse Failed to parse package.json data.
19 error JSON.parse package.json must be actual JSON, not just JavaScript.
20 verbose exit [ 1, true ]
```

And yes...wiring pi is installed and functioning

Ideas??

**Comment by jmc265** [comment]
Hi. Is this still an issue or were you able to fix it?

**Comment by Flavelius** [comment]
Hi, i'm trying to install your nodered module https://github.com/jmc265/node-red-contrib-rpi-433
which depends on this one that fails for me too but on wiringpi. Looking that up it seems it's deprecated, discontinued and not available anymore. Any alternative?

**Comment by jmc265** [comment]
@Flavelius I am afriad I am not aware of any alternative to wiringPi. The package has been discontinued, but is still available and should work fine. If you have a particular problem with the install please open a new issue and give as much detail as possible as well as steps you have already taken to resolve the issue.

**Comment by Flavelius** [comment]
Not sure if it's worth opening a ticket for this, as you likely cannot do anything about it. For me it already was the apt install wiringpi line that didn't work (wiringpi not existing), so the nodered install was always failing at not finding wiringpi.h; but now i found that i can use https://github.com/WiringPi/WiringPi and do a manual build from it which finally made it work.

**Comment by jmc265** [comment]
Ah, thank you for posting a solution if others have the same issue.
